version: "3.8"

services:
  alterego:
    image: ghcr.io/molsnoo/alter-ego:latest
    container_name: alterego
    env_file:
      - .env
    volumes:
      - data:/home/node/app/Configs
    restart: unless-stopped

volumes:
  data: