name: Publish Image
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v4
      - 
        name: Build image tag
        run: echo "IMAGE_TAG=$(git log -1 --pretty=%h)" >> $GITHUB_ENV 
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3 
        with:
          registry: ghcr.io
          username: ${{ secrets.GITHUB_REPOSITORY_OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/alter-ego:${{ env.IMAGE_TAG }}
            ghcr.io/${{ secrets.GITHUB_REPOSITORY_OWNER }}/alter-ego:latest
          file: ./Dockerfile
          build-args: |
            image_commit=${{ env.IMAGE_TAG }}
