name: Tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy configuration files for testing
        run: |
          cp Defaults/default_constants.json Configs/constants.json
          cp Defaults/default_credentials.json Configs/credentials.json
          cp Defaults/default_demodata.json Configs/demodata.json
          cp Defaults/default_playerdefaults.json Configs/playerdefaults.json
          cp Defaults/default_serverconfig.json Configs/serverconfig.json
          cp Defaults/default_settings.json Configs/settings.json

      - name: Run tests with Jest
        run: npm test -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/